"""first revision

Revision ID: fb35c3e94581
Revises: 
Create Date: 2025-02-17 19:45:33.566329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb35c3e94581'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('to-do', sa.Column('description', sa.String(50)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to-do',
    sa.Column('_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('todo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_id', name='to-do_pkey')
    )
    # ### end Alembic commands ###
